[project]
authors = ["FuelName"]
entry = "main.sw"
license = "Apache-2.0"
name = "registrar"

[dependencies]
shared = { path = "../shared" }
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.21.0" }
