[project]
authors = ["FuelName"]
entry = "main.sw"
license = "Apache-2.0"
name = "proxy"

[dependencies]
shared = { path = "../shared" }
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.24.0" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.6.1" }
